demo-servlets/src/main/java/fr/isika/al/beans/Article.java
ackage fr.isika.al.beans;

import java.io.Serializable;

public class Article implements Serializable, ITruc
{
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String libelle;
	private double prix;
	
	public Article()
	{
		
	}

	public Article(int id, String libelle, double prix) {
		super();
		this.id = id;
		this.libelle = libelle;
		this.prix = prix;
	}


	public void plop(String s, int x)
	{
		for (int i = 0; i < x; i++) 
		{
			System.out.println(s);
		}
	}

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getLibelle() {
		return libelle;
	}
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}
	public double getPrix() {
		return prix;
	}
	public void setPrix(double prix) {
		this.prix = prix;
	}
	
	
	
	
}

demo-servlets/src/main/java/fr/isika/al/beans/ITruc.java
package fr.isika.al.beans;

public interface ITruc {
	public void plop(String s, int x);
}

demo-servlets/src/main/java/fr/isika/al/beans/LignePanier.java
package fr.isika.al.beans;

import java.io.Serializable;

public class LignePanier implements Serializable
{
	private static final long serialVersionUID = 1L;

	private int quantite;
	private Article article;
	
	public int getQuantite() 
	{
		return quantite;
	}
	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}
	public Article getArticle() {
		return article;
	}
	public void setArticle(Article article) {
		this.article = article;
	}
	
	
	
}

demo-servlets/src/main/java/fr/isika/al/beans/Panier.java
package fr.isika.al.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Panier implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	private Date dateCreation;
	
	private List<LignePanier> lignes = new ArrayList<LignePanier>();

	public int getNbArticles()
	{
		int resultat = 0;
		
		for (LignePanier ligne : lignes) 
		{
			resultat += ligne.getQuantite();
		}
		
		return resultat;
	}
	
	public Date getDateCreation() {
		return dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public List<LignePanier> getLignes() {
		return lignes;
	}

	public void setLignes(List<LignePanier> lignes) {
		this.lignes = lignes;
	}
	
	
	
}

demo-servlets/src/main/java/fr/isika/al/beans/Utilisateur.java
package fr.isika.al.beans;

import java.io.Serializable;

public class Utilisateur implements Serializable{
	private static final long serialVersionUID = 1L;
	
	private String nom;
	private String prenom;
	
	public String getNom() 
	{
		return nom;
	}
	
	public void setNom(String nom) 
	{
		this.nom = nom;
	}
	
	public String getPrenom() 
	{
		return prenom;
	}
	
	public void setPrenom(String prenom) 
	{
		this.prenom = prenom;
	}
	
	
}

demo-servlets/src/main/webapp/TestTags.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

<%@ taglib prefix="isika" uri="/WEB-INF/taglibs/myTags.tld" %>    
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

<isika:fc valeur="jean baptiste"/>
<br/>
<isika:fc valeur="marcel"/>

	<isika:lien adresse="http://www.projet-isika.com">cliquez ici...</isika:lien>

	<isika:lien adresse="Catalogue">voir le catalogue</isika:lien>
</body>
</html>

demo-servlets/src/main/webapp/WEB-INF/vues/boxPanier.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

	<jsp:useBean id="panier" scope="session" class="fr.isika.al.beans.Panier"></jsp:useBean>

	<div>
	Mon panier : ${panier.nbArticles} articles
	</div>

demo-servlets/src/main/webapp/WEB-INF/vues/catalogue.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="articles" scope="application" class="java.util.ArrayList"></jsp:useBean>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

	<h1>Catalogue</h1>

	<jsp:include page="boxPanier.jsp"></jsp:include>

	<ul>
	<c:forEach items="${articles}" var="article">
		<li>
		<a href="FicheArticle?id=${article.id}">${article.libelle}</a> 	
		</li>
	</c:forEach>
	</ul>

</body>
</html>

demo-servlets/src/main/webapp/WEB-INF/vues/entete.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

demo-servlets/src/main/webapp/WEB-INF/vues/ficheArticle.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

<form action="FicheArticle" method="post">
	
	<h1>Fiche article</h1>

	<jsp:include page="boxPanier.jsp"></jsp:include>

	<h2>${article.libelle }</h2>
	<h3>prix : ${article.prix}</h3>

	<input type="hidden" name="idArticle" value="${article.id}"/>	
	<input type="text" name="quantite"/>

	<input type="submit" value="Ajouter au panier"/>

</form>

</body>
</html>

demo-servlets/src/main/webapp/WEB-INF/vues/pied.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

</body>
</html>

demo-servlets/src/main/webapp/WEB-INF/vues/recapPanier.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>


<h1>Recap panier</h1>

<jsp:include page="boxPanier.jsp"></jsp:include>

<a href="Catalogue">retour</a>

<table>
	<tr>
		<td>libelle</td>
		<td>PU</td>
		<td>Qte</td>
		<td>Total</td>
	</tr>
<c:forEach items="${panier.lignes}" var="ligne">
	<tr>
		<td>${ligne.article.libelle}</td>
		<td>${ligne.article.prix}</td>
		<td>${ligne.quantite}</td>
		<td>${ligne.article.prix * ligne.quantite}</td>
	</tr>
</c:forEach>
</table>
	

</body>
</html>

demo-servlets/src/main/webapp/premierejsp.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" %>

<%!	int x = 42; 
	int y = 2;
	String couleur;%>
	
<%
	for(int i =0; i< request.getCookies().length; i++)
	{
		Cookie c = request.getCookies()[i];
		if (c.getName().equals("couleur"))
		{
			couleur = c.getValue();
		}
	}
%>	
    
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<style>
	body
	{
		color : <%= couleur%>;
	}
</style>
</head>
<body>
<h1>Hello jsp</h1>

<h2>
<%= x %>
</h2>

</body>
</html>